"use client";
import { useEffect, useRef, useState } from "react";
import { useRouter } from "next/navigation";
import { useMutation, useQueryClient } from "@tanstack/react-query";
import { useForm, useWatch } from "react-hook-form";
import { zodResolver } from "@hookform/resolvers/zod";
import { Camera, Check, Clapperboard, Image as ImageIcon, ImagePlus, Sparkles, Trash2, Upload } from "lucide-react";
import { Button, PageHeader } from "@/components/common/ui";
import { MediaPreview } from "@/components/content/media-preview";
import { useToast } from "@/components/common/providers";
import { contentFormSchema, type ContentFormValues } from "@/features/content/schemas";
import { mockApi } from "@/lib/api/mock-api";
import { cn, purposeLabel, toneLabel } from "@/lib/utils";
import type { ContentAsset, ContentFormat, ContentPurpose, ContentTone } from "@/types";

const steps = ["사진", "빵 정보", "스타일", "확인"];
const defaultValues: ContentFormValues = { breadName:"", price:"", quantity:"", highlights:"", promotion:"", additionalRequest:"", tone:"friendly", purpose:"today_bread", format:"feed" };
type UploadedMedia = { url: string; type: ContentAsset["type"]; alt: string };

export default function NewContentPage() {
  const router = useRouter(); const queryClient = useQueryClient(); const toast = useToast();
  const [step,setStep] = useState(1); const [previews,setPreviews] = useState<UploadedMedia[]>([]); const [photoError,setPhotoError] = useState(""); const inputRef=useRef<HTMLInputElement>(null);
  const { register, control, setValue, trigger, reset, formState:{errors} } = useForm<ContentFormValues>({ resolver:zodResolver(contentFormSchema), defaultValues });
  const values=useWatch({control}) as ContentFormValues;
  useEffect(()=>{ try { const draft=localStorage.getItem("bbangsomoon.new-draft"); if(draft) reset({...defaultValues,...JSON.parse(draft)}); } catch {} },[reset]);
  useEffect(()=>{ localStorage.setItem("bbangsomoon.new-draft",JSON.stringify(values)); },[values]);

  const mutation=useMutation({ mutationFn:()=>mockApi.createContent({ ...values, price: values.price === "" ? undefined : Number(values.price), media:previews.map(({type,url})=>({type,url})) }), onSuccess:(content)=>{ localStorage.removeItem("bbangsomoon.new-draft"); queryClient.invalidateQueries({queryKey:["contents"]}); toast(values.format==="reel"?"영상 콘텐츠가 완성됐어요!":"AI 콘텐츠가 완성됐어요!"); router.push(`/contents/${content.id}/edit`); } });
  const addFiles=(files:FileList|null)=>{ if(!files)return; const isReel=values.format==="reel"; const valid=Array.from(files).filter(f=>isReel?(f.type.startsWith("video/")&&f.size<=100*1024*1024):(f.type.startsWith("image/")&&f.size<=10*1024*1024)); if(valid.length===0){setPhotoError(isReel?"100MB 이하의 MP4, WebM 또는 MOV 영상을 선택해 주세요.":"10MB 이하의 JPG, PNG 또는 WebP 사진을 선택해 주세요.");return;} const slots=isReel?1:3-previews.length; const media=valid.slice(0,slots).map(file=>({url:URL.createObjectURL(file),type:(isReel?"video":"image") as ContentAsset["type"],alt:file.name})); setPreviews(p=>isReel?media:[...p,...media]); setPhotoError(""); };
  const removePhoto=(index:number)=>{ const asset=previews[index]; if(asset?.url.startsWith("blob:")) URL.revokeObjectURL(asset.url); setPreviews(p=>p.filter((_,i)=>i!==index)); };
  const changeFormat=(format:ContentFormat)=>{if(values.format===format)return;previews.forEach(asset=>asset.url.startsWith("blob:")&&URL.revokeObjectURL(asset.url));setPreviews([]);setPhotoError("");setValue("format",format)};
  const next=async()=>{ if(step===1 && previews.length===0){setPhotoError(values.format==="reel"?"게시할 동영상을 선택해 주세요.":"빵 사진을 한 장 이상 올려 주세요.");return;} if(step===2 && !(await trigger("breadName")))return; setStep(s=>Math.min(4,s+1)); window.scrollTo({top:0,behavior:"smooth"}); };
  return <div className="mx-auto max-w-3xl"><PageHeader title="새 콘텐츠 만들기" description="한 단계씩 천천히 입력해 주세요. 약 1분이면 충분해요." backHref="/dashboard"/>
    <ol className="mb-8 grid grid-cols-4 gap-1" aria-label="진행 단계">{steps.map((label,i)=>{const n=i+1;return <li key={label} className="text-center"><div className={cn("mx-auto grid size-8 place-items-center rounded-full text-xs font-black transition",n<step?"bg-emerald-600 text-white":n===step?"bg-[#ef6b32] text-white shadow-[0_0_0_5px_rgba(239,107,50,.12)]":"bg-stone-200 text-stone-500")}>{n<step?<Check className="size-4"/>:n}</div><p className={cn("mt-2 text-xs font-bold",n===step?"text-[#d95320]":"text-stone-400")}>{label}</p><div className={cn("relative -top-[31px] -z-10 ml-[58%] h-[2px] w-[84%]",i===steps.length-1&&"hidden",n<step?"bg-emerald-500":"bg-stone-200")}/></li>})}</ol>

    <div className="surface rounded-[28px] p-5 sm:p-8">
      {step===1&&<section><div className="mb-6"><span className="text-xs font-black text-[#ef6b32]">1단계</span><h2 className="mt-1 text-2xl font-black">어떤 콘텐츠를 만들까요?</h2><p className="mt-2 text-sm leading-6 text-stone-500">사진 또는 짧은 영상 중에서 선택해 주세요.</p></div>
        <div className="mb-6 grid grid-cols-2 gap-2"><button type="button" onClick={()=>changeFormat("feed")} className={cn("focus-ring flex min-h-20 items-center gap-3 rounded-2xl border p-4 text-left",values.format==="feed"?"border-[#ef6b32] bg-orange-50 text-[#d95320]":"border-stone-200 text-stone-600")}><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-white shadow-sm"><ImageIcon className="size-5"/></span><span><b className="block">사진 게시물</b><small className="mt-1 block text-stone-500">사진 최대 3장</small></span></button><button type="button" onClick={()=>changeFormat("reel")} className={cn("focus-ring flex min-h-20 items-center gap-3 rounded-2xl border p-4 text-left",values.format==="reel"?"border-[#ef6b32] bg-orange-50 text-[#d95320]":"border-stone-200 text-stone-600")}><span className="grid size-10 shrink-0 place-items-center rounded-xl bg-white shadow-sm"><Clapperboard className="size-5"/></span><span><b className="block">영상 게시물</b><small className="mt-1 block text-stone-500">동영상 1개</small></span></button></div>
        <input ref={inputRef} type="file" accept={values.format==="reel"?"video/mp4,video/webm,video/quicktime":"image/jpeg,image/png,image/webp"} multiple={values.format==="feed"} className="sr-only" onChange={e=>{addFiles(e.target.files);e.currentTarget.value=""}}/>
        {previews.length===0?<button type="button" onClick={()=>inputRef.current?.click()} className="focus-ring grid min-h-64 w-full place-items-center rounded-2xl border-2 border-dashed border-orange-200 bg-orange-50/50 p-6 text-center transition hover:bg-orange-50"><div><div className="mx-auto grid size-16 place-items-center rounded-2xl bg-white text-[#ef6b32] shadow-sm">{values.format==="reel"?<Clapperboard className="size-7"/>:<Camera className="size-7"/>}</div><p className="mt-5 font-black">{values.format==="reel"?"동영상 선택":"사진 선택 또는 카메라로 촬영"}</p><p className="mt-2 text-xs text-stone-500">{values.format==="reel"?"MP4, WebM, MOV · 최대 100MB":"JPG, PNG, WebP · 한 장당 최대 10MB"}</p></div></button>:<div className={cn("grid gap-3",values.format==="reel"?"grid-cols-1":"grid-cols-2 sm:grid-cols-3")}>{previews.map((asset,i)=><div key={asset.url} className={cn("group relative overflow-hidden rounded-2xl bg-stone-100",asset.type==="video"?"aspect-[9/16] max-h-[520px]":"aspect-square")}><MediaPreview asset={asset} controls={asset.type==="video"}/><button type="button" onClick={()=>removePhoto(i)} aria-label="미디어 삭제" className="focus-ring absolute right-2 top-2 grid size-9 place-items-center rounded-full bg-black/65 text-white backdrop-blur"><Trash2 className="size-4"/></button></div>)}{values.format==="feed"&&previews.length<3&&<button type="button" onClick={()=>inputRef.current?.click()} className="focus-ring grid aspect-square place-items-center rounded-2xl border-2 border-dashed border-stone-200 text-stone-500 hover:border-orange-200 hover:text-[#ef6b32]"><span className="flex flex-col items-center gap-2 text-xs font-bold"><ImagePlus className="size-6"/>사진 추가</span></button>}</div>}
        {photoError&&<p className="mt-3 text-sm font-semibold text-red-600">{photoError}</p>}
        {values.format==="feed"&&<button type="button" onClick={()=>{setPreviews([{url:"/images/bakery-hero.png",type:"image",alt:"샘플 빵 사진"}]);setPhotoError("")}} className="focus-ring mt-4 flex w-full items-center justify-center gap-2 rounded-xl bg-stone-100 px-4 py-3 text-sm font-bold text-stone-600 hover:bg-stone-200"><Upload className="size-4"/>샘플 사진으로 먼저 체험하기</button>}
      </section>}

      {step===2&&<section><div className="mb-6"><span className="text-xs font-black text-[#ef6b32]">2단계</span><h2 className="mt-1 text-2xl font-black">오늘의 빵을 알려주세요</h2><p className="mt-2 text-sm text-stone-500">빵 이름만 필수예요. 아는 내용만 편하게 적어 주세요.</p></div><div className="grid gap-5 sm:grid-cols-2">
        <label className="sm:col-span-2"><span className="mb-2 block text-sm font-bold">홍보할 빵 이름 <b className="text-[#ef6b32]">*</b></span><input {...register("breadName")} className="field" placeholder="예: 버터 크루아상"/>{errors.breadName&&<span className="mt-2 block text-xs font-semibold text-red-600">{errors.breadName.message}</span>}</label>
        <label><span className="mb-2 block text-sm font-bold">가격</span><div className="relative"><input {...register("price")} inputMode="numeric" className="field pr-11" placeholder="3800"/><span className="absolute right-4 top-3.5 text-sm text-stone-400">원</span></div></label>
        <label><span className="mb-2 block text-sm font-bold">오늘 준비한 수량</span><input {...register("quantity")} className="field" placeholder="예: 20개"/></label>
        <label className="sm:col-span-2"><span className="mb-2 block text-sm font-bold">꼭 알려주고 싶은 특징</span><textarea {...register("highlights")} rows={3} className="field resize-none" placeholder="예: 프랑스산 버터로 겹겹이 바삭해요"/></label>
        <label className="sm:col-span-2"><span className="mb-2 block text-sm font-bold">할인 또는 행사</span><input {...register("promotion")} className="field" placeholder="예: 오후 6시부터 20% 할인"/></label>
        <label className="sm:col-span-2"><span className="mb-2 block text-sm font-bold">AI에게 추가로 부탁할 내용</span><textarea {...register("additionalRequest")} rows={3} className="field resize-none" placeholder="예: 비 오는 날 분위기를 살려 주세요"/></label>
      </div></section>}

      {step===3&&<section><div className="mb-7"><span className="text-xs font-black text-[#ef6b32]">3단계</span><h2 className="mt-1 text-2xl font-black">어떤 느낌으로 소문낼까요?</h2><p className="mt-2 text-sm text-stone-500">손님에게 전하고 싶은 분위기와 목적을 골라 주세요.</p></div>
        <fieldset><legend className="text-sm font-black">글의 말투</legend><div className="mt-3 grid grid-cols-2 gap-2">{(Object.entries(toneLabel) as [ContentTone,string][]).map(([value,label])=><button key={value} type="button" onClick={()=>setValue("tone",value)} className={cn("focus-ring min-h-14 rounded-2xl border px-3 text-sm font-bold transition",values.tone===value?"border-[#ef6b32] bg-orange-50 text-[#d95320] shadow-[0_0_0_2px_rgba(239,107,50,.08)]":"border-stone-200 bg-white text-stone-600 hover:border-stone-300")}>{label}</button>)}</div></fieldset>
        <fieldset className="mt-8"><legend className="text-sm font-black">이번 게시물의 목적</legend><div className="mt-3 space-y-2">{(Object.entries(purposeLabel) as [ContentPurpose,string][]).map(([value,label])=><button key={value} type="button" onClick={()=>setValue("purpose",value)} className={cn("focus-ring flex min-h-14 w-full items-center justify-between rounded-2xl border px-4 text-left text-sm font-bold transition",values.purpose===value?"border-[#ef6b32] bg-orange-50 text-[#d95320]":"border-stone-200 bg-white text-stone-700 hover:border-stone-300")}><span>{label}</span><span className={cn("grid size-5 place-items-center rounded-full border",values.purpose===value?"border-[#ef6b32] bg-[#ef6b32] text-white":"border-stone-300")}>{values.purpose===value&&<Check className="size-3"/>}</span></button>)}</div></fieldset>
      </section>}

      {step===4&&<section><div className="mb-6"><span className="text-xs font-black text-[#ef6b32]">4단계</span><h2 className="mt-1 text-2xl font-black">이대로 글을 만들까요?</h2><p className="mt-2 text-sm text-stone-500">입력한 내용을 확인해 주세요. AI가 자연스러운 홍보 글로 다듬어 드려요.</p></div>
        <div className="grid gap-5 sm:grid-cols-[180px_1fr]"><div className={cn("relative overflow-hidden rounded-2xl bg-stone-100",values.format==="reel"?"aspect-[9/16]":"aspect-square")}><MediaPreview asset={previews[0]} controls={values.format==="reel"}/><span className="absolute bottom-2 right-2 rounded-full bg-black/65 px-2 py-1 text-xs font-bold text-white">{values.format==="reel"?"영상 1개":`사진 ${previews.length}장`}</span></div><dl className="grid content-start gap-3 rounded-2xl bg-stone-50 p-5 text-sm"><div><dt className="text-xs font-bold text-stone-400">오늘의 빵</dt><dd className="mt-1 text-lg font-black">{values.breadName}</dd></div><div className="grid grid-cols-2 gap-3"><div><dt className="text-xs font-bold text-stone-400">말투</dt><dd className="mt-1 font-bold">{toneLabel[values.tone]}</dd></div><div><dt className="text-xs font-bold text-stone-400">형식</dt><dd className="mt-1 font-bold">{values.format==="reel"?"영상 게시물":"사진 게시물"}</dd></div></div>{values.highlights&&<div><dt className="text-xs font-bold text-stone-400">강조할 내용</dt><dd className="mt-1 leading-6">{values.highlights}</dd></div>}</dl></div>
        <div className="mt-6 rounded-2xl border border-orange-100 bg-orange-50 p-4 text-sm leading-6 text-orange-900"><Sparkles className="mr-2 inline size-4 text-[#ef6b32]"/>버튼을 누르면 약 1~2초 뒤 홍보 글이 완성돼요. 결과 화면에서 마음껏 고칠 수 있습니다.</div>
      </section>}
    </div>

    <div className="sticky bottom-[76px] z-20 -mx-4 mt-5 flex gap-2 border-t border-stone-200 bg-[#fbfaf6]/95 px-4 py-4 backdrop-blur lg:bottom-0 lg:mx-0 lg:border-0 lg:bg-transparent lg:px-0">{step>1&&<Button variant="secondary" className="min-w-24" onClick={()=>setStep(s=>s-1)} disabled={mutation.isPending}>이전</Button>}{step<4?<Button className="flex-1" onClick={next}>다음 단계</Button>:<Button className="flex-1 min-h-13" onClick={()=>mutation.mutate()} disabled={mutation.isPending}>{mutation.isPending?"AI가 글을 쓰고 있어요":"AI 콘텐츠 만들기"}</Button>}</div>
  </div>;
}
