import Image from "next/image";
import Link from "next/link";
import { AlertCircle, ArrowLeft, LoaderCircle } from "lucide-react";
import { cn, statusMeta } from "@/lib/utils";
import type { ContentStatus } from "@/types";

export function Logo({ light = false, href = "/dashboard" }: { light?: boolean; href?: string }) { return <Link href={href} className={cn("focus-ring inline-flex items-center gap-2 rounded-xl text-[22px] font-black tracking-[-.06em]", light ? "text-white" : "text-stone-900")}><Image src="/icon.svg" alt="" width={32} height={32} className="size-8 rounded-xl shadow-sm" />빵소문</Link>; }
export function Button({ className, variant = "primary", ...props }: React.ButtonHTMLAttributes<HTMLButtonElement> & { variant?: "primary"|"secondary"|"ghost"|"danger" }) {
  const styles = { primary: "bg-[#ef6b32] text-white shadow-[0_8px_20px_rgba(239,107,50,.22)] hover:bg-[#d95320]", secondary: "border border-stone-200 bg-white text-stone-800 hover:bg-stone-50", ghost: "text-stone-600 hover:bg-stone-100", danger: "bg-red-50 text-red-700 hover:bg-red-100" };
  return <button className={cn("focus-ring inline-flex min-h-11 items-center justify-center gap-2 rounded-xl px-4 py-2.5 text-sm font-bold transition disabled:cursor-not-allowed disabled:opacity-50", styles[variant], className)} {...props} />;
}
export function Badge({ status }: { status: ContentStatus }) { const meta = statusMeta[status]; return <span className={cn("inline-flex rounded-full px-2.5 py-1 text-xs font-bold", meta.className)}>{meta.label}</span>; }
export function PageHeader({ title, description, backHref, action }: { title: string; description?: string; backHref?: string; action?: React.ReactNode }) { return <header className="mb-7 flex items-start justify-between gap-4"><div>{backHref && <Link href={backHref} className="focus-ring mb-3 inline-flex items-center gap-1 rounded-lg text-sm font-semibold text-stone-500 hover:text-stone-800"><ArrowLeft className="size-4"/>돌아가기</Link>}<h1 className="text-2xl font-black tracking-[-.04em] text-stone-900 sm:text-3xl">{title}</h1>{description && <p className="mt-2 text-sm leading-6 text-stone-500 sm:text-base">{description}</p>}</div>{action}</header>; }
export function LoadingState({ label = "불러오는 중이에요" }: { label?: string }) { return <div className="grid min-h-64 place-items-center"><div className="flex flex-col items-center gap-3 text-sm font-semibold text-stone-500"><LoaderCircle className="size-7 animate-spin text-[#ef6b32]"/>{label}</div></div>; }
export function ErrorState({ message = "잠시 문제가 생겼어요." }: { message?: string }) { return <div className="surface grid min-h-52 place-items-center rounded-3xl p-6 text-center"><div><AlertCircle className="mx-auto mb-3 size-8 text-red-500"/><p className="font-bold">{message}</p><p className="mt-1 text-sm text-stone-500">페이지를 새로고침해 다시 시도해 주세요.</p></div></div>; }
export function EmptyState({ title, description, action }: { title: string; description: string; action?: React.ReactNode }) { return <div className="surface grid min-h-64 place-items-center rounded-3xl p-7 text-center"><div><div className="mx-auto mb-4 grid size-14 place-items-center rounded-2xl bg-orange-50 text-2xl">🥐</div><h3 className="text-lg font-black">{title}</h3><p className="mt-2 text-sm leading-6 text-stone-500">{description}</p>{action && <div className="mt-5">{action}</div>}</div></div>; }
export function ConfirmDialog({ open, title, description, confirmLabel = "확인", onConfirm, onClose }: { open: boolean; title: string; description: string; confirmLabel?: string; onConfirm: () => void; onClose: () => void }) { if(!open) return null; return <div className="fixed inset-0 z-[110] grid place-items-end bg-black/35 p-4 sm:place-items-center" onMouseDown={onClose}><div role="dialog" aria-modal="true" onMouseDown={(e)=>e.stopPropagation()} className="w-full max-w-sm rounded-3xl bg-white p-6 shadow-2xl"><h2 className="text-xl font-black">{title}</h2><p className="mt-2 text-sm leading-6 text-stone-500">{description}</p><div className="mt-6 grid grid-cols-2 gap-2"><Button variant="secondary" onClick={onClose}>취소</Button><Button variant="danger" onClick={onConfirm}>{confirmLabel}</Button></div></div></div>; }
